### ISSUE TITLE
Factorizacion y Documentacion 

### ISSUE THREAD

**Issue by Akamiz96** [Rinconjr/Risk-EDD-Grupo1#12]
El archivo `Menu.hxx` no cuenta con un solo comentario entre funciones. Solo con los comentarios de separacion de secciones. 

- Cuando ponen cosas como `//Diego` `//Nico` eso pueden hacerlo con las etiquetas `TODO` no solo el apodo y ya. 
- Funcion `comando_turno` no es facil de mantener ni modificar si algo llega a necesitarse
- Se puede factorizar la imagen en otro archivo para que quede mas limpio este que es el principal de Menu
- Cuidado con los nombres de los archivos, no se como lo estan haciendo pero esta `Menu.h` y `main.cpp`. Mantengan la misma estructura para todos. O con Mayusculas o con Minusculas.

**Comment by SantiagoYB** [comment]
Se agregaron los comentarios entre funciones, se elimino las cosas como "//Diego" "//Nico" "//Santiago", el comando turno se arreglo en el otro issue, se cambio la imagen del risk a una función y se dejo los archivos en minúscula

**Comment by SantiagoYB** [comment]
Se cierra

**Comment by SantiagoYB** [comment]
Se agregaron los comentarios entre funciones, se elimino las cosas como "//Diego" "//Nico" "//Santiago", el comando turno se arreglo en el otro issue, se cambio la imagen del risk a una función y se dejo los archivos en minúscula
