### ISSUE TITLE
Comando de compilacion 

### ISSUE THREAD

**Issue by Akamiz96** [Rinconjr/Risk-EDD-Grupo1#4]
El comando de compilacion presentado en el [README](https://github.com/Rinconjr/Risk-EDD-Grupo1/blob/main/README.md) no deja compilar por la direccion del archivo `main.cpp` 

O especificar donde debo ejecutar ese comando. 

Lo ejecute en la raiz del proyecto y el resultado fue 
```c++
cc1plus: fatal error: main.cpp: No such file or directory
compilation terminated.
```

**Comment by Rinconjr** [comment]
En el readme se especifico desde donde se debe ejecutar el comando de compilacion para que este no de error.
