### ISSUE TITLE
Incluir en el header de inicio la version que se esta ejecutando 

### ISSUE THREAD

**Issue by Akamiz96** [Rinconjr/Risk-EDD-Grupo1#5]
Es buena practica que en el header de impresion incluyan la version que se ejecuta. Asi en el caso por ejemplo mio que hay varias versiones podre saber facilmente cual es la que estoy ejecutando. 

![imagen](https://github.com/Rinconjr/Risk-EDD-Grupo1/assets/15280019/818c107d-4ea9-4b2f-bc0f-4d16d837b221)

Algo en el centro debajo del mapamundi

**Comment by JuanDiegoEcheverryP** [comment]
Se ha agregado la versión debajo del mapamundi en el issue #5
