### ISSUE TITLE
Comandos sin parametros 

### ISSUE THREAD

**Issue by Akamiz96** [Rinconjr/Risk-EDD-Grupo1#7]
Al ejecutar el comando `ayuda` sobre el comando `inicializar` me dice que debo ejecutarlo de la siguiente manera:

```
$ ayuda inicializar
 Comando: inicializar <nombre_archivo>
   Descripcion: Inicializa un nuevo juego. Ingrese el nombre del archivo para reanudar.
``` 

Sin embargo, se me ocurre probarlo sin el nombre del archivo y el resultado es: 

```
$ inicializar
 Ingrese el nombre para la partida:
``` 
Deberia ser ese un comportamiento estandar del programa? o mejor no deberia decirme que asi no se ejecuta y que mejor ejecutarlo de otra forma?

**Comment by JuanDiegoEcheverryP** [comment]
- Se ha corregido en el último commit los prompts de 'Inicializar' para dar mayor claridad al usuario de la información que debe ingresar.
- El comando de "Ayuda" brinda información adicional de como inicializar una partida nueva, o una partida existente
