### ISSUE TITLE
Comando inicializar 

### ISSUE THREAD

**Issue by Akamiz96** [Rinconjr/Risk-EDD-Grupo1#8]
Al ejecutar el comando `inicializar` con una archivo no existente dentro de la carpeta me genera el siguiente mensaje 

```
$ inicializar help.txt
El nombre de la partida no puede estar separada por espacios.
$ inicializar help
El nombre de la partida no puede estar separada por espacios.
$
``` 
El mensaje de error no me dice como solucionarlo y no se que tenga que ver el nombre de la partida con los espacios. 

Revisar la escritura de los mensajes de error y la ejecucion del comando inicializar.

**Comment by JuanDiegoEcheverryP** [comment]
- En el último commit se han arreglado los propmpts para la opción para darle al usuario mayor claridad de la información que debe ingresar.
- De momento la opción de inicializar una partida existente no carga la partida, la función se encuentra en construcción.
